### ISSUE TITLE
ページ構成を考える

### ISSUE THREAD

**Issue by yassi-github** [sai-lab/sai-lab.github.io#1]
dokuwikiの丸パクリでいいですか

~~これが便利か検証する~~
~~https://github.com/sai-lab/sai-lab.github.io/projects/1#card-79403100~~
-> mdの扱いはjsのmarkdown-itが便利そうなのでそちらを検討

**Comment by i13302** [comment]
>dokuwikiの丸パクリでいいですか

構いません．

**Comment by yassi-github** [comment]
dokuwikiの構成をそのまま使用する
