### ISSUE TITLE
github.ioの利用規約

### ISSUE THREAD

**Issue by i13302** [sai-lab/sai-lab.github.io#3]
研究室HPとして利用できるか，確認しておくこと．

**Comment by yassi-github** [comment]
https://docs.github.com/ja/site-policy/github-terms/github-terms-of-service#d-user-generated-content
https://docs.github.com/ja/site-policy/github-terms/github-terms-for-additional-products-and-features#pages
https://docs.github.com/ja/pages/getting-started-with-github-pages/about-github-pages#

特に問題はなさそうに思う
