### ISSUE TITLE
メンバー用Wikiのアクセス方法を決める

### ISSUE THREAD

**Issue by yassi-github** [sai-lab/sai-lab.github.io#6]
現状、メンバー用Wikiにアクセスするには、basic認証が必要である。
しかし、github.ioではサーバサイドをカスタマイズできないので、ログインができない。

よって、メンバー用の情報にアクセスする方法を別に考える必要がある。

**Comment by i13302** [comment]
メンバーwikiは今となっては，esaやTeamsで事足りるので不要かと．
